all_ids_dicts = {'radiogordost_tg_channels_dict':{
												  'katyushaband': 'Катюша',
												  'gazmanovOG': 'Олег Газманов',
												  'sashakruglovamusic':'саша круг',
												  'natalikachuramusic': 'Наталья Качура',
												  'anitatsoy': 'Анита Цой',
												  'utamusic_telegram': 'Юта',
												  'julia_chicherina': 'Чичерина',
												  'shaman_channel': 'Шаман',
												  'gumfrontru': 'гумфронтру',
												  'dolinaofficial': 'Долина',
												  'ybaranovskaya_tv': 'Барановская',
												  'dmitry_malikov_official': 'Маликов',
												  'voytenkos': 'Войтенко',
												  'maxfadeev1': 'Макс фадеев',
												  'chaifru': 'чайф',
												  'averbukh_ilya': 'Авербух',
												  'dubtsovaofficial': 'Дубцова',
												  'Polk1_2_3': 'Полк 123',
												  'Nuihorsnym': 'Хор Турецкого',
												  'IgorSukachev': 'Игорь Сукачев',
												  'ZVEROROK': 'Зверобой',
												  'thecuba_ru': 'Куба',
												  'gvleps_official ': 'Григорий Лепс',
												  'vladdeminofficial': 'Влад Демин',
												  'RKadyrov_95': 'Рамзан Кадыров',
												  'vvgladkov': 'Вячеслав Гладков',
												  'mos_sobyanin': 'Сергей Собянин',
												  'Aksenov82': 'Сергей Аксенов',
												  'gubernator_46': 'Роман Старовойт',
												  'vorobiev_live': 'Андрей Воробьев',
												  'pushilindenis': 'Денис Пушилин',
												  'razvozhaev': 'Михаил Развожаев',
												  'a_beglov': 'Александр Беглов',
												  'SALDO_VGA': 'Владимир Сальдо',
												  'mkotyukov': 'Михаил Котюков',
												  'VVV5807': 'Владимир Владимиров',
												  'golubev_vu': 'Василий Голубев',
												  'tsivilev_kuzbass': 'Сергей Цивилев',
												  'kobzevii': 'Игорь Кобзев',
												  'kozhemiakoofficial': 'Олег Кожемяко',
												  'avbogomaz': 'Александр Богомаз',
												  'glebnikitin_nn': 'Глеб Никитин',
												  'kondratyevvi': 'Вениамин Кондратьев',
												  'rustamminnikhanov': 'Рустам Минниханов',
												  'HocenkoVP': 'Виталий Хоценко',
												  'MV_007_Pskov': 'Михаил Ведерников',
												  'busargin_r': 'Роман Бусаргин',
												  'BalitskyEV': 'Евгений Балицкий',
												  'mazur_70': 'Владимир Мазур',
												  'igor_artamonov48': 'Игорь Артамонов',
												  'Shapsha_VV': 'Владислав Шапша',
												  'radiyhabirov': 'Радий Хабиров',
												  'melikov05': 'Сергей Меликов',
												  'KuvshinnikovLive': 'Олег Кувшинников',
												  'gusev_36': 'Александр Гусев',
												  'limarenko_official': 'Валерий Лимаренко',
												  'alexeytexlerofficial': 'Алексей Текслер',
												  'tomenko_22': 'Виктор Томенко',
												  'aleksandrsokolov43': 'Александр Соколов',
												  'pavelmalkov_official': 'Павел Малков',
												  'artyukhov_da': 'Дмитрий Артюхов',
												  'Klychkov_Andrey': 'Андрей Клычков',
												  'OrlovAmur': 'Василий Орлов',
												  'glava_lnr_info': 'Леонид Пасечник',
												  'aisen_nikolaev': 'Айсен Николаев',
												  'drozdenko_au_lo': 'Александр Дрозденко',
												  'Degtyarev_Info': 'Михаил Дегтярев',
												  'babushkin30': 'Игорь Бабушкин',
												  'anohin67': 'Василий Анохин',
												  'TravnikovAndrey': 'Андрей Травников',
												  'omelnichenko': 'Олег Мельниченко',
												  'andrey_chibis': 'Андрей Чибис',
												  'mahonin59': 'Дмитрий Махонин',
												  'av_moor': 'Александр Моор',
												  'Russkih_Aleksey': 'Алексей Русских',
												  'yvzaitsev': ' Юрий Зайцев',
												  'vsolodovbrief': 'Владимир Солодов',
												  'Kokov_Kazbek': 'Казбек Коков',
												  'muratkumpilov': ' Мурат Кумпилов',
												  'kuyvashevevgeny': 'Евгений Куйвашев',
												  'alexeytsydenov': 'Алексей Цыденов',
												  'oanikolaev': 'Олег Николаев',
												  'egorovmb': 'Максим Егоров',
												  'DVPasler': 'Денис Паслер',
												  'brechalov': 'Александр Бречалов',
												  'avdeev_o_vazhnom': 'Александр Авдеев',
												  'silavpravdevshumkov': 'Вадим Шумков',
												  'Tsybulskiy_A': 'Александр Цыбульский',
												  'rashid_temrezov': 'Рашид Темрезов',
												  'BatuKhasikov08': 'Бату Хасиков',
												  'zdunov': 'Артем Здунов',
												  'sergeymeniaylo': 'Сергей Меняйло',
												  'evraevmikhail': 'Михаил Евраев',
												  'nikitinnov': 'Андрей Никитин',
												  'komarova_ugra': 'Наталья Комарова',
												  'khovalyg_live': 'Владислав Ховалыг',
												  'am_osipov': 'Александр Осипов',
												  'vladislav_kuznecov': 'Владислав Кузнецов',
												  'sk_sitnikov': 'Сергей Ситников',
												  'nosovlive_ru': 'Сергей Носов',
												  'MAKalimatovvv': 'Махмуд-Али Калиматов',
												  'konovalov_khakasia19': 'Валентин Коновалов',
												  'azarovlife63': 'Дмитрий Азаров',
												  'khorokhordin': 'Олег Хорохордин',
												  'rostislav_goldshtein': 'Ростислав Гольдштейн',
												  'Aparfenchikov': 'Артур Парфенчиков',
												  'Bezdudnyi': 'Юрий Бездудный',
												  'VladimirUyba': 'Владимир Уйба',
												  'Alexey_Dyumin': ' Алексей Дюмин',
												  }






				 }

out_list = []
for key in all_ids_dicts['radiogordost_tg_channels_dict'].keys():
	out_list.append(f'@{key}')

print(', '.join(out_list))